### PR TITLE
Start to pythonify this code

### PR DESCRIPTION
**Pull request by PaulSonOfLars**
Reformat the basic code to remove some of the bad codestyle previously present.
Your env variables are numerous  enough that I cant test this myself. But there shouldn't be any breaking changes, and they'll be easy fixes that i'll happily help with.
Also, now respect the 80char limit, unlike previous PR.

### CODE REVIEW

**Comment by xdevs23** [comment]
Do a quick test by running the bot with the `sanity-check` argument.

**Comment by PaulSonOfLars** [comment]
Not much of a test, but `sanity-check` works.

**Comment by xdevs23** [comment]
Eliminate the merge commit please.

> Not much of a test, but sanity-check works.

That usually means that all imports were resolved.

**Comment by PaulSonOfLars** [comment]
I know how imports work, all that test does is the python equivalent of "it compiles". Merge removed.

**Comment by xdevs23** [comment]
Umm by 'eliminate merge' I meant 'rebase on master' but I'll do that now.

**Comment by xdevs23** [comment]
"Merged"

**Pull request closed without merging**
